name: Run Newman Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  newman-test:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checar o repositório
      - name: Check out the repository
        uses: actions/checkout@v3

      # Passo 2: Listar arquivos no repositório (para verificar se a coleção existe)
      - name: List repository files
        run: ls -alh

      # Passo 3: Verificar se o arquivo collection-postman.json existe
      - name: Check if collection-postman.json exists
        run: |
          if [ ! -f "collection-postman.json" ]; then
            echo "collection-postman.json not found!";
            exit 1;
          else
            echo "collection-postman.json found.";
          fi

      # Passo 4: Instalar o Node.js e Newman
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Newman and HTMLEXTRA Reporter
        run: |
          npm install -g newman newman-reporter-htmlextra

      # Passo 5: Executar os testes com Newman e gerar o relatório HTMLEXTRA
      - name: Run Newman tests
        run: |
          newman run collection-postman.json --reporters htmlextra --reporter-htmlextra-export newman-report.html --verbose
        continue-on-error: true

      # Passo 6: Configurar GitHub Pages
      - name: Configure GitHub Pages
        run: |
          mkdir -p ./public
          mv newman-report.html ./public/index.html

      # Passo 7: Publicar no GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public