name: Run Newman Tests and Publish Results
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  newman-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: List repository files
        run: ls -alh

      - name: Check if collection-postman.json exists
        run: |
          if [ ! -f "collection-postman.json" ]; then
            echo "collection-postman.json not found!";
            exit 1;
          else
            echo "collection-postman.json found.";
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman and reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Newman tests
        run: |
          newman run collection-postman.json --verbose -r htmlextra --reporter-htmlextra-export index.html --reporter-htmlextra-darkTheme > runreport1.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: success()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          keep_files: true