name: Run Newman Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  newman-test:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checar o repositório
      - name: Check out the repository
        uses: actions/checkout@v3

      # Passo 2: Listar arquivos no repositório (para verificar se a coleção existe)
      - name: List repository files
        run: ls -alh

      # Passo 3: Instalar o Node.js e Newman
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Newman
        run: npm install -g newman

      # Instalar o reporter HTMLEXTRA para Newman
      - name: Install HTMLEXTRA Reporter for Newman
        run: npm install -g newman-reporter-htmlextra

      # Passo 4: Executar os testes com Newman e gerar o relatório HTMLEXTRA
      - name: Run Newman tests
        run: |
          newman run collection-postman.json --reporters htmlextra --reporter-htmlextra-export newman-report.html --verbose || {
            echo "Newman test run failed.";
            exit 1;
          }

      # Passo 5: Publicar o relatório HTML gerado
      - name: Upload Newman report
        uses: actions/upload-artifact@v3
        with:
          name: newman-report
          path: newman-report.html
